spring.application.name=api-sistemaTurnos

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/turnito
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Mercado Pago Configuration
mercadopago.access-token=TEST-5229781330906520-060423-3f73d06426abf4369905dfb617701c54-295344204
mercadopago.notification-url=https://unrated-angular-exhaust.ngrok-free.dev/api/pagos/webhook
